name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath

    - name: Install Composer Dependencies
      run: composer install --no-dev --prefer-dist --optimize-autoloader

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Clear Node Modules and Cache
      run: |
        rm -rf node_modules
        npm cache clean --force

    - name: Install NPM Dependencies
      run: npm install

    - name: Update Webpack Configuration
      run: |
        echo "Updating Webpack configuration in webpack.mix.js"
        # Ensure Webpack can detect .js, .vue, and other common extensions
        echo "mix.webpackConfig({
          resolve: {
            extensions: ['*', '.js', '.jsx', '.vue', '.json']
          }
        });" >> webpack.mix.js

    - name: Build Assets
      run: npm run production

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.sahiljani.dev
        username: account@sahiljani.dev
        password: 12wyactrg0qn
        local-dir: ./  
        server-dir: /public_html/

    - name: Generate Application Key
      run: php artisan key:generate --force
      env:
        APP_ENV: production
        APP_DEBUG: false

    - name: Run Migrations on Server
      env:
        DB_CONNECTION: mysql
        DB_HOST: localhost
        DB_PORT: 3306
        DB_DATABASE: sahilja1_firefly
        DB_USERNAME: sahilja1_firefly
        DB_PASSWORD: firefly@123
      run: php artisan migrate --force
      shell: bash
